title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  I am a network software programmer currently hired by Huawei Technology Inc. My interests
  are netconf protocol, artificial intelligence, algorithms and continuous integration
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Chushu Liu # add your name
author-img: liuchushu.jpg # add your photo
about-author: I am a network software programmer currently hired by Huawei Technology Inc. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Choosue # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
